// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: proto/downloader.proto

package downloader_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DownloaderService_AddTask_FullMethodName = "/downloader.DownloaderService/AddTask"
)

// DownloaderServiceClient is the client API for DownloaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DownloaderServiceClient interface {
	AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error)
}

type downloaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDownloaderServiceClient(cc grpc.ClientConnInterface) DownloaderServiceClient {
	return &downloaderServiceClient{cc}
}

func (c *downloaderServiceClient) AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTaskResponse)
	err := c.cc.Invoke(ctx, DownloaderService_AddTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DownloaderServiceServer is the server API for DownloaderService service.
// All implementations must embed UnimplementedDownloaderServiceServer
// for forward compatibility.
type DownloaderServiceServer interface {
	AddTask(context.Context, *AddTaskRequest) (*AddTaskResponse, error)
	mustEmbedUnimplementedDownloaderServiceServer()
}

// UnimplementedDownloaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDownloaderServiceServer struct{}

func (UnimplementedDownloaderServiceServer) AddTask(context.Context, *AddTaskRequest) (*AddTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTask not implemented")
}
func (UnimplementedDownloaderServiceServer) mustEmbedUnimplementedDownloaderServiceServer() {}
func (UnimplementedDownloaderServiceServer) testEmbeddedByValue()                           {}

// UnsafeDownloaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DownloaderServiceServer will
// result in compilation errors.
type UnsafeDownloaderServiceServer interface {
	mustEmbedUnimplementedDownloaderServiceServer()
}

func RegisterDownloaderServiceServer(s grpc.ServiceRegistrar, srv DownloaderServiceServer) {
	// If the following call pancis, it indicates UnimplementedDownloaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DownloaderService_ServiceDesc, srv)
}

func _DownloaderService_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloaderServiceServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloaderService_AddTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloaderServiceServer).AddTask(ctx, req.(*AddTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DownloaderService_ServiceDesc is the grpc.ServiceDesc for DownloaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DownloaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "downloader.DownloaderService",
	HandlerType: (*DownloaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _DownloaderService_AddTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/downloader.proto",
}
