syntax = "proto3";

package downloader;
option go_package = "lgo_download_manager/downloader_grpc";

service DownloaderService {
  rpc AddTask (AddTaskRequest) returns (AddTaskResponse);
}

enum ProtocolType {
  HTTP  = 0;
  HTTPS = 1;
  FTP   = 2;
  WEBDAV = 3;
}

message AddTaskRequest {
  string url           = 1;
  string file_name     = 2;
  ProtocolType protocol = 3;

  // auth / extra request fields
  string username      = 4;
  string password      = 5;
  string user_agent    = 6;
  string cookies       = 7;
  string referer       = 8;

  // options
  bool ftp_passive_mode = 9;
  int32 chunk_count     = 10;
}

message AddTaskResponse {
  bool   success  = 1;
  string message  = 2;
  string task_id  = 3;
}
